-- MySQL Workbench Synchronization
-- Generated: 2019-03-06 09:46
-- Model: horseracing
-- Version: 1.0
-- Project: Horse Racing
-- Author: Jose Antonio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `horseracing`.`horse` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race_id` INT(10) UNSIGNED NOT NULL,
  `speed` DECIMAL(3,1) UNSIGNED NOT NULL DEFAULT 0,
  `strength` DECIMAL(3,1) UNSIGNED NOT NULL DEFAULT 0,
  `endurance` DECIMAL(3,1) UNSIGNED NOT NULL DEFAULT 0,
  `distance` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `time_elapsed` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_horse_race_idx` (`race_id` ASC),
  CONSTRAINT `fk_horse_race`
    FOREIGN KEY (`race_id`)
    REFERENCES `horseracing`.`race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `horseracing`.`race` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '1 = Running | 0 = Finished\n',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tick` INT(10) UNSIGNED NULL DEFAULT 0 COMMENT 'Number of times that progress button was pushed.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
